import 'package:flutter/material.dart';
import 'package:share_prompt/components/home_app_bar.dart';
import 'package:share_prompt/components/prompt_card.dart';
import 'package:share_prompt/model/prompt_card_model.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});


  @override
  Widget build(BuildContext context) {
    final List<PromptCardModel> _promptCards = [
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
      PromptCardModel(title: '브랜드 로고 디자인 프롬프트',
        main: '로고만들때 사용해보세요.\n유용한 프롬프트입니다 :)',
        tagCount: 2,
        userName: '한지석',
        likeCount: 12,
      ),
    ];
    return Scaffold(
      appBar: HomeAppBar(),
        body: SafeArea(
            child: ListView.builder(
              scrollDirection: Axis.vertical,
                itemBuilder: (BuildContext context, int index) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 26, vertical: 6),
                    child: PromptCard(title: _promptCards[index].title,
                        main: _promptCards[index].main,
                        tagCount: _promptCards[index].tagCount,
                        userName: _promptCards[index].userName,
                        likeCount: _promptCards[index].likeCount
                    ),
                  );
                }
            ),
        )
    );
  }
}
